.TH "bf" "1" "20041219" "Stephan Beyer <s-beyer@gmx.net>" "devel"
.SH "NAME"
.LP 
bf \- yet another Brainfuck interpreter
.SH "SYNTAX"
.LP 
bf [\fB\-h\fR] [\fIoptions\fP] <\fIfilename\fP>
.SH "DESCRIPTION"
.LP 
bf ('Yet another Brainfuck interpreter') is a simple
interpreter for the esoteric Brainfuck language.
.SH "OPTIONS"
.LP 
.TP 
\fB\-c\fR<\fInum\fP>
Specify the number \fInum\fP of the last cell you are
allowed to use in your Brainfuck program.

So if you use \fI\-c0\fR (or just \fI\-c\fR), you'll
have one cell (one byte in memory) to use on your tape.
'>'ing and '<'ing will be impossible. The original
Brainfuck interpreter by Urban Mueller used an array
of 30000 bytes (\fI\-c29999\fR).
.br 
Our default value is 9999. Usually you need less.
.TP 
\fB\-i\fR
Output Brainfuck code input to \fIstderr\fR.

This feature is useful if you can't find out why some
Brainfuck code doesn't work the way it should e.g. ignored
loops, or a Brainfuck character within a comment.

Note: Up to 32 +, \-, < and > are summarized and displayed as
only one. This feature was introduced in version 20040423.
.TP
\fB\-n\fR
Some Brainfuck contests specify a 0 byte as End Of Input. So -n
translates a \\n byte input into a 0 byte input. Disadvantage: the input
can only consist of one line.
.TP 
\fB\-w\fR
Disallow byte wrap\-around. This causes errors if you try
to decrement ('\-') a 0x00 byte or to increment ('+') a 
0xFF byte.

This feature is useful if you want to take part in Brainfuck
contests where such wrapping\-around is disallowed.
.br 
By default (without \fI\-w\fR), incrementing 0xFF results
in 0x00 and decrementing 0x00 results in 0xFF.
.TP 
\fB\-,\fR<\fImode\fR>
Specify input mode. <\fImode\fR> can be:

\fI0\fR (zero) Normal input using \fIgetchar(3)\fR.
.br 
\fI1\fR Single\-char input. You won't see what you type.
.br 
\fI2\fR Single\-char input. You will see what you type.
.br 
\fI3\fR The same as 1, but doesn't allow escape characters if compiled with slang.
.br 
\fI4\fR The same as 2, but doesn't allow escape characters, if compiled with slang. (recommended)

Default is 0. (In some versions the default was 4.)
.SH "LIMITATIONS"
.TP 
It's not allowed to '<' below the first cell.
.TP 
It's not allowed to '>' beyond the last cell.
.SH "AUTHORS"
.LP 
Stephan Beyer <s\-beyer@gmx.net>
